on: [ push ]

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   id: send_message
                uses: ./
                with:
                    token: ${{ secrets.TOKEN }}
                    chat_id: ${{ secrets.CHAT_ID }}
                    parse_mode: html
                    disable_notification: true
                    text: |
                        Mona the <a href="https://google.com">Octocat</a>

            -   run: |
                    echo "Message ID: ${{ steps.send_message.outputs.message_id }}"
